export const SITE_NAME = "Zuno"
export const SITE_TAGLINE = "AI website builder"
export const SITE_DESCRIPTION =
  "Zuno is a full-stack AI website builder. Clarify in chat, pick React or Next with JS or TS, build a live site, then iterate through chat."
export const SITE_URL = "https://zuno.ashishjha.xyz"
export const GITHUB_URL = "https://github.com/ashishxjhaa/Zuno"
export const GITHUB_PROFILE_URL = "https://github.com/ashishxjhaa"
export const GITHUB_ISSUES_URL = "https://github.com/ashishxjhaa/Zuno/issues"
export const TWITTER_URL = "https://x.com/ashishxjha"
export const CONTACT_EMAIL = "ashishxyzjha@gmail.com"
export const AUTHOR_NAME = "Ashish Jha"
export const AUTHOR_URL = "https://ashishjha.xyz/"
